# serverless.yml
service: es-cleanup-lambda

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-2'}
  profile: dev
  deploymentBucket:
    name: 
  environment:
    es_endpoint: vpc-dev-log-collector-ghfcybggmvewicsph4eelzwvya.ap-northeast-2.es.amazonaws.com                         
    index: all
    delete_after: "2"
    index_format: "%Y.%m.%d"
  stackTags: # Optional CF stack tags
    Owner: jongam.oh@kurlycorp.com
    Purpose: es-cleanup
    Environment: DEV
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "es:*"
      Resource: "arn:aws:es:ap-northeast-2:030787254034:domain/dev-log-collector/*"
      # you must specify the full ARN  of the AWS ES Domain
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
      Resource: "arn:aws:es:ap-northeast-2:030787254034:domain/dev-log-collector/*"      



functions:
  es-cleanup-lambda:
    handler: es-cleanup.lambda_handler
    vpc:
      securityGroupIds:
        - sg-089ec35d429cae6c3
        - sg-0a4c023e84e04736d
      subnetIds:
        - subnet-0b1f0453c0b3d7594
        - subnet-0c2933dd014afed9c    
    name: es-cleanup-lambda
    description: ES old index removal
    runtime: python2.7
    memorySize: "256"
    timeout: 300
    package:
      exclude:
        - ./**
      include:
        - es-cleanup.py
        - LICENSE.md
        - README.md
        - CONTRIBUTING.md
    events:
      # Invoke Lambda function every night at 01.00 AM
      - schedule: cron(0 15 * * ? *)
      # Invoke Lambda function every 5 min everyday .
      # - schedule: cron(0/1 * * * ? *)

resources:
  Description: "AWS Lambda: Elasticsearch Index Cleanup"      
